# Generated by Django 5.1.4 on 2024-12-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_banner_color_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='banner_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
