# Generated by Django 5.1.4 on 2024-12-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskcategory_taskpriority_taskstatus_tasktag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskpriority',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='description',
        ),
    ]
