# Generated by Django 5.1.4 on 2024-12-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_datecompled_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
