# Generated by Django 5.1.4 on 2024-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_is_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
