# Generated by Django 5.1.4 on 2025-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_taskcomment_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
